version: "3"

volumes:
    to_data_results:

services:
  to_data:
    build: .
    environment:
        - TO_DB_SERVER=${TO_DB_SERVER}
        - TO_DB_USER=${TO_DB_USER}
        - TO_DB_PASSWORD=${TO_DB_PASSWORD}
        - TO_DB_NAME=${TO_DB_NAME}
        - DT_DB_SERVER=${DT_DB_SERVER}
        - DT_DB_USER=${DT_DB_USER}
        - DT_DB_PASSWORD=${DT_DB_PASSWORD}
        - DT_DB_NAME=${DT_DB_NAME}
    volumes:
        - to_data_results:/app/results
    network_mode: "host"
